odtheking/Odin

odin/build.gradle.kts, odinclient/build.gradle.kts, odinmain/build.gradle.kts, odinmain/src/main/kotlin/me/odinmain/ui/waypoint/WaypointGUI.kt, odinmain/src/main/kotlin/me/odinmain/utils/render/gui/nvg/NVGUtils.kt
Update OneConfig and fix IDE run configs
=> Gradle tech support

odinmain/src/main/kotlin/me/odinmain/features/impl/render/CustomHighlight.kt
=> no more fel esp when legit :'(

odinclient/src/main/kotlin/me/odinclient/features/impl/skyblock/ChestEsp.kt
=> fixed chest esp not being esp

odinmain/src/main/kotlin/me/odinmain/features/impl/floor7/p3/GoldorTimer.kt
thanks azure for thinking it was the regex
=> no more weird shouldLoad system + actually works again

odinclient/src/main/kotlin/me/odinclient/ModCore.kt, odinmain/src/main/kotlin/me/odinmain/features/impl/skyblock/HidePlayers.kt
wanted to add this before the merge but i was too late
=> only at devs for hideplayers

odinmain/src/main/kotlin/me/odinmain/features/impl/floor7/Relic.kt, odinmain/src/main/kotlin/me/odinmain/features/impl/floor7/WitherDragons.kt
i did 1 run of testing and it worked so its probably good
=> probably fixed relic timer

odinmain/src/main/kotlin/me/odinmain/features/impl/floor7/p3/termGUI/OrderGui.kt, odinmain/src/main/kotlin/me/odinmain/features/impl/floor7/p3/termGUI/RubixGui.kt
=> centered term text

odinmain/src/main/kotlin/me/odinmain/features/impl/floor7/DragonHealth.kt, odinmain/src/main/kotlin/me/odinmain/features/impl/floor7/WitherDragons.kt
i hope getting every loaded entity is fine, made this in 2 seconds so i didnt really check
=> Dragon health stuffs

odinclient/src/main/kotlin/me/odinclient/features/impl/skyblock/ChocolateFactory.kt
fixes clicking (annoying asf now)
added upgrade delay
=> Chocolate Factory Changes

odinclient/src/main/kotlin/me/odinclient/features/impl/floor7/p3/CancelWrongTerms.kt
Disable Block Wrong Clicks in Rubix
=> Disable Block Wrong Clicks in Rubix

odinmain/src/main/kotlin/me/odinmain/features/impl/dungeon/LeapMenu.kt, odinmain/src/main/kotlin/me/odinmain/features/impl/floor7/WitherDragonEnum.kt, odinmain/src/main/kotlin/me/odinmain/features/impl/floor7/p3/termGUI/CustomTermGui.kt, odinmain/src/main/kotlin/me/odinmain/features/impl/skyblock/WardrobeKeybinds.kt, odinmain/src/main/kotlin/me/odinmain/utils/skyblock/PlayerUtils.kt
also fixed a woopsie in witherdragonsenum
=> Fixed more clicks

odinmain/src/main/kotlin/me/odinmain/features/impl/dungeon/ClickedSecrets.kt
let clicked secrets show in boss
=> let clicked secrets show in boss

odinclient/src/main/kotlin/me/odinclient/features/impl/skyblock/AutoExperiments.kt
Add Metaphysical Serum count for Auto Close
=> add serum count to Auto Experiment

odin/src/main/kotlin/me/odin/features/impl/render/EtherWarpHelper.kt, odinclient/src/main/kotlin/me/odinclient/features/impl/render/EtherWarpHelper.kt
fix etherwarp helper the phase setting is inverted for some bizarre reason bhai
=> fix etherwarp helper 

odinmain/src/main/kotlin/me/odinmain/features/impl/floor7/DragonPriority.kt, odinmain/src/main/kotlin/me/odinmain/features/impl/floor7/WitherDragons.kt, odinmain/src/main/kotlin/me/odinmain/features/impl/floor7/p3/TerminalTimes.kt
Made both wither dragon arrow alerts formatting consistent Fixed no paul with time multiplying power by 3.5x
=> Real time term times

odinmain/src/main/kotlin/me/odinmain/features/impl/floor7/p3/TerminalTimes.kt, odinmain/src/main/kotlin/me/odinmain/utils/skyblock/dungeon/Dungeon.kt
also changed how blood done is calculated so it never subtracts score.
=> fixed real time terminal splits

odinmain/src/main/kotlin/me/odinmain/events/EventDispatcher.kt, odinmain/src/main/kotlin/me/odinmain/features/impl/skyblock/ItemsHighlight.kt, odinmain/src/main/kotlin/me/odinmain/utils/skyblock/dungeon/DungeonUtils.kt
=> items highlight only secrets

odinmain/src/main/kotlin/me/odinmain/utils/ServerUtils.kt
fixes this happening on startup
=> Fix: Ping Calculation on Startup

odinmain/src/main/kotlin/me/odinmain/features/impl/floor7/p3/TerminalSolver.kt
=> melody fix again

odinmain/src/main/kotlin/me/odinmain/features/impl/floor7/DragonCheck.kt
hopefully its not too delayed, there is fixes to make it instant but idk how best to do it without more variables.
=> fix drag prio

odinmain/src/main/kotlin/me/odinmain/commands/impl/DungeonWaypointCommand.kt, odinmain/src/main/kotlin/me/odinmain/config/DungeonWaypointConfig.kt, odinmain/src/main/kotlin/me/odinmain/features/impl/dungeon/dungeonwaypoints/DungeonWaypoints.kt, odinmain/src/main/kotlin/me/odinmain/features/impl/dungeon/dungeonwaypoints/SecretWaypoints.kt, odinmain/src/main/kotlin/me/odinmain/utils/render/RenderUtils.kt
changes some ways on how dungeon waypoints are handled, instead of them having a boolean for secret, dungeon waypoints can be set as types, rn those being none, normal, secret, or etherwarp. etherwarp waypoints get removed when etherwarped to.
also cleaned up the way waypoints are stored in config, and fixed a couple of rendering bugs
=> Improvement: Dungeon Waypoints

odinmain/src/main/kotlin/me/odinmain/utils/skyblock/DianaBurrowEstimate.kt
fixes a npe that happened in diana burrow estimate
=> Fix: Diana Burrow Estimate NPE

odinmain/src/main/kotlin/me/odinmain/features/impl/skyblock/Ragaxe.kt, odinmain/src/main/kotlin/me/odinmain/utils/skyblock/ItemUtils.kt
Tried to write with the same style as you with help of gpt :)
Basically the mod will send a client message or party message based on how much strength you gain from casting rag axe
=> Added an option for rag axe strength gain as well as ItemUtil for getting strength

odinmain/src/main/kotlin/me/odinmain/features/impl/dungeon/BloodCamp.kt, odinmain/src/main/kotlin/me/odinmain/features/impl/dungeon/PosMessages.kt, odinmain/src/main/kotlin/me/odinmain/features/impl/dungeon/dungeonwaypoints/DungeonWaypoints.kt, odinmain/src/main/kotlin/me/odinmain/features/impl/floor7/DragonCheck.kt
also made the code significantly better probably
=> blood camp helper is now as smooth as physically possible

src/main/kotlin/me/odinmain/commands/impl/OdinCommand.kt
Change map value to fix "/od t1" not working to enter Basic Tier of Kuudra
=> fix basic tier kuudra instance name

odin/src/main/kotlin/me/odin/features/impl/skyblock/HidePlayers.kt, odinclient/src/main/kotlin/me/odinclient/features/impl/skyblock/HidePlayers.kt, src/main/kotlin/me/odinmain/features/impl/dungeon/WarpCooldown.kt, src/main/kotlin/me/odinmain/utils/ServerUtils.kt, src/main/kotlin/me/odinmain/utils/skyblock/LocationUtils.kt, src/main/kotlin/me/odinmain/utils/skyblock/dungeon/Dungeon.kt, src/main/kotlin/me/odinmain/utils/skyblock/dungeon/DungeonEnums.kt
and individual player death detection for use at some point
=> warp cooldown and hide players thingy

src/main/kotlin/me/odinmain/features/impl/nether/NoPre.kt
Updated the crate priority to be updated (mostly pro-mode changes). 
Confirmed correct prio from Kuudra Gang/CratePriority ct module
=> Update Crate prio for modern priority

src/main/kotlin/me/odinmain/features/impl/dungeon/DungeonRequeue.kt, src/main/kotlin/me/odinmain/features/impl/nether/KuudraRequeue.kt
Adds more regex to pause auto-requeue with "Disable on leave/kick" or if you leave/are kicked/party disbanded
=> Auto-Requeue pausing 

src/main/kotlin/me/odinmain/features/impl/nether/KuudraDisplay.kt
Updated Kuudra Scaled HP to be increased to a maximum of 240m
=> Fix Kuudra HP

src/main/kotlin/me/odinmain/features/impl/floor7/p3/ArrowAlign.kt
Invert sneak option for arrow align's "Block Wrong Clicks"
=> Arrow align invert sneak

src/main/kotlin/me/odinmain/commands/impl/OdinCommand.kt
makes customleap not case sensitive
=> Make custom leaporder less scuffed

odin/src/main/java/me/odin/mixin/mixins/entity/MixinEntityArrow.java, odin/src/main/resources/mixins.odin.json, odinclient/src/main/java/me/odinclient/mixin/mixins/entity/MixinEntityArrow.java, odinclient/src/main/resources/mixins.odinclient.json, src/main/kotlin/me/odinmain/OdinMain.kt, src/main/kotlin/me/odinmain/commands/impl/DungeonWaypointCommand.kt, src/main/kotlin/me/odinmain/config/DungeonWaypointConfig.kt, src/main/kotlin/me/odinmain/events/impl/ArrowEvent.kt, src/main/kotlin/me/odinmain/features/impl/dungeon/TeammatesHighlight.kt, src/main/kotlin/me/odinmain/features/impl/floor7/DragonCheck.kt, src/main/kotlin/me/odinmain/features/impl/floor7/WitherDragonEnum.kt, src/main/kotlin/me/odinmain/features/impl/floor7/WitherDragons.kt, src/main/kotlin/me/odinmain/utils/skyblock/ArrowTracker.kt, src/main/kotlin/me/odinmain/utils/skyblock/dungeon/DungeonUtils.kt
continuation of #174, changed the branch because intellij git thingy sucks and i cant use it
=> better arrows hit thingy

src/main/kotlin/me/odinmain/features/ModuleManager.kt, src/main/kotlin/me/odinmain/features/impl/dungeon/SpiritBear.kt
=> Feat: Spirit Bear (show the state and timer)

odinclient/src/main/kotlin/me/odinclient/features/impl/dungeon/AutoSell.kt, src/main/kotlin/me/odinmain/features/impl/render/RandomPlayers.kt, src/main/kotlin/me/odinmain/features/impl/skyblock/CommandKeybinds.kt, src/main/kotlin/me/odinmain/features/impl/skyblock/ItemsHighlight.kt, src/main/kotlin/me/odinmain/utils/skyblock/dungeon/DungeonUtils.kt
when i was walking in hub i saw this red cube on my screen
=> Fix: ItemsHighlight inDungeons check + Update items list ? idk 

src/main/kotlin/me/odinmain/features/impl/dungeon/ExtraStats.kt, src/main/kotlin/me/odinmain/utils/Utils.kt
Made Extra Stats have more stats and configurable
Default configuration effect diagram:
=> Optimize Extra Stats

odinclient/src/main/kotlin/me/odinclient/features/impl/dungeon/AutoGFS.kt
Fixed grammar mistake, missing an "t"
=> Added a missing t
